CREATE TABLE trialmango.products (
  idproduct INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  productName VARCHAR(255) NOT NULL,
  productDescription VARCHAR(255) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  productReview TEXT NOT NULL,
  productDiscount DECIMAL(5, 2) NOT NULL,
  discountedPrice DECIMAL(10, 2) NOT NULL,
  is_deleted TINYINT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
